import = [
  "~/.config/alacritty/Themes/gruvbox_material_hard_dark_2.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.bold]
family = "CascadiaMono"
style = "Bold"

[font.bold_italic]
family = "CascadiaMono"
style = "Bold Italic"

[font.italic]
family = "CascadiaMono"
style = "Italic"

[font.normal]
family = "CascadiaMono"
style = "Regular"
